FROM node:20.17.0-slim

RUN apt-get update && apt-get install -y python3 make g++ && apt-get clean

WORKDIR /app

COPY package.json package-lock.json* ./


RUN npm install --omit=optional

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
